CREATE TABLE CUISINE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64),
);

CREATE TABLE DIFFICULTY(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64),
);

CREATE TABLE RECIPE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  CUISINE_ID INTEGER,
  numOfIngredients INTEGER NOT NULL,
  isVegetarian BIT NOT NULL,
  DIFFICULTY_ID INTEGER,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  INGREDIENTS VARCHAR(1000) NOT NULL,
  IMAGE_NAME VARCHAR(100)
);



ALTER TABLE RECIPE ADD FOREIGN KEY (CUISINE_ID) REFERENCES CUISINE(ID);
ALTER TABLE RECIPE ADD FOREIGN KEY (DIFFICULTY_ID) REFERENCES DIFFICULTY(ID);

